version: '3'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: robot-data-app-backend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: robot-data-app-frontend
    ports:
      - "3000:80"

  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=robotdatadb
    ports:
      - '5432:5432'

networks:
  node-network:
    driver: bridge
