FROM python:3.11
WORKDIR /app

COPY backend/requirements.txt backend/app.py backend/.flaskenv ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["flask", "run", "--host", "0.0.0.0"]